apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
spec:
  type: NodePort
  selector:
    app: my-nginx   # 👈 must match Deployment’s label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

