apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx   # 👈 label changed
  template:
    metadata:
      labels:
        app: my-nginx # 👈 label changed
    spec:
      containers:
      - name: nginx
        image: nginx-jenkins-minikube:latest
        ports:
        - containerPort: 80

